#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=36 blur_radius=15 color=0x403b0f2c y_offset=8 margin=8 corner_radius=10 padding_left=4 padding_right=4 border_color=0x40efddc2 border_width=1

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=0
  padding_right=0
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Mono:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
do
  sid="$((i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    align=center
    background.color=0x40efddc2
    background.corner_radius=6
    background.height=28
    width=28
    label.drawing=off
    script="$PLUGIN_DIR/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app left \
           --set front_app icon.drawing=on script="$PLUGIN_DIR/front_app.sh" background.color=0xc0814c5e background.corner_radius=6 padding_left=3 icon.padding_left=12 label.padding_right=12 background.height=28 align=center \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar --add item clock right \
           --set clock update_freq=10 script="$PLUGIN_DIR/clock.sh" \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \
           --add item network right \
           --set network script="$PLUGIN_DIR/network.sh" \
           --subscribe network wifi_change \

# sketchybar --add bracket space space --set space blur_radius=30 background.color=0x40000000 background.corner_radius=10
# sketchybar --add bracket tests front_app --set tests blur_radius=30 background.color=0x40000000 background.corner_radius=10

sketchybar --set clock background.color=0xc0814c5e background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=0
sketchybar --set volume background.color=0xc0814c5e background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3
sketchybar --set battery background.color=0xc0814c5e background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3
sketchybar --set network background.color=0xc0814c5e background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3
# sketchybar --set brew_packages background.color=0xc0814c5e background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3

# sketchybar --add bracket clock_bracket clock --set clock_bracket blur_radius=30 background.color=0xffffffff background.corner_radius=10
# sketchybar --add bracket volume_bracket volume --set volume_bracket blur_radius=30 background.color=0x40000000 background.corner_radius=10
# sketchybar --add bracket battery_bracket battery --set battery_bracket blur_radius=30 background.color=0x40000000 background.corner_radius=10

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

sketchybar --hotload true

sketchybar --trigger packages INFO="$COUNT"