#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Bar Appearance

sketchybar --bar position=top height=36 blur_radius=15 color=0x40373454 y_offset=8 margin=8 corner_radius=10 padding_left=4 padding_right=4 border_color=0xff373454 border_width=1

# Defaults

default=(
	padding_left=0
	padding_right=0
	icon.font="SF Pro:Semibold:14.0"
	label.font="SF Mono:Bold:14.0"
	icon.color=0xffffffff
	label.color=0xffffffff
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
)
sketchybar --default "${default[@]}"

# Left Items

sketchybar --add item front_app left \
	--set front_app icon.drawing=on script="$PLUGIN_DIR/front_app.sh" background.color=0xc0373465 background.corner_radius=6 padding_left=0 icon.padding_left=12 label.padding_right=12 background.height=28 align=center \
	--subscribe front_app front_app_switched

# Right Items

sketchybar --add item clock right \
	--set clock script="$PLUGIN_DIR/clock/clock.sh" \
	--add item volume right \
	--set volume script="$PLUGIN_DIR/volume.sh" \
	--subscribe volume volume_change \
	--add item battery right \
	--set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
	--subscribe battery system_woke power_source_change \
	--add item network right \
	--set network script="$PLUGIN_DIR/network.sh" \
	--subscribe network wifi_change

sketchybar --set clock background.color=0xc0373465 background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=0
sketchybar --set volume background.color=0xc0373465 background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3
sketchybar --set battery background.color=0xc0373465 background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3
sketchybar --set network background.color=0xc0373465 background.corner_radius=6 label.padding_right=12 icon.padding_left=12 background.height=28 padding_right=3

cd ./plugins && make

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

sketchybar --hotload true
